-- Generated by arboretum's Certify.lean_size_proof: a machine-checked
-- proof that the tree-calculus program below computes the node count of
-- every tree it is applied to. Self-contained; check with `lean` alone.
set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false

inductive Tree where
  | leaf : Tree
  | stem : Tree -> Tree
  | fork : Tree -> Tree -> Tree

open Tree

abbrev L : Tree := leaf
abbrev S : Tree -> Tree := stem
abbrev F : Tree -> Tree -> Tree := fork

def sz : Tree -> Nat
  | leaf => 1
  | stem t => sz t + 1
  | fork l r => sz l + sz r + 1

def stack : Nat -> Tree -> Tree
  | 0, s => s
  | n + 1, s => stem (stack n s)

def snat (n : Nat) : Tree := stack n leaf

theorem stack_stack (a b : Nat) (s : Tree) :
    stack a (stack b s) = stack (a + b) s := by
  induction a with
  | zero => simp [stack]
  | succ n ih => simp [stack, ih, Nat.succ_add]

theorem sz_stack (n : Nat) (s : Tree) : sz (stack n s) = n + sz s := by
  induction n with
  | zero => simp [stack]
  | succ n ih => simp [stack, sz, ih]; omega

-- Big-step application: App a b c holds when the tree a applied to the
-- tree b evaluates to c by the five rules of triage calculus. Every
-- premise is itself an evaluated application, so a derivation is a
-- complete computation record.
inductive App : Tree -> Tree -> Tree -> Prop where
  | grow0 {b} : App leaf b (stem b)
  | grow1 {x b} : App (stem x) b (fork x b)
  | rK {y z} : App (fork leaf y) z y
  | rS {x y z r1 r2 r} : App x z r1 -> App y z r2 -> App r1 r2 r ->
      App (fork (stem x) y) z r
  | r3a {w x y} : App (fork (fork w x) y) leaf w
  | r3b {w x y u r} : App x u r -> App (fork (fork w x) y) (stem u) r
  | r3c {w x y u v r1 r} : App y u r1 -> App r1 v r ->
      App (fork (fork w x) y) (fork u v) r

theorem App.det {a b c c2 : Tree} (h : App a b c) (h2 : App a b c2) : c = c2 := by
  induction h generalizing c2 with
  | grow0 => cases h2; rfl
  | grow1 => cases h2; rfl
  | rK => cases h2; rfl
  | rS h1 h2 h3 ih1 ih2 ih3 =>
    cases h2 with
    | rS g1 g2 g3 => obtain rfl := ih1 g1; obtain rfl := ih2 g2; exact ih3 g3
  | r3a => cases h2; rfl
  | r3b h ih => cases h2 with | r3b g => exact ih g
  | r3c h1 h2 ih1 ih2 =>
    cases h2 with
    | r3c g1 g2 => obtain rfl := ih1 g1; exact ih2 g2

-- The loop value inside prog
def SELF : Tree := (F (S (F L (F (F L L) (F (S (F (S (S L)) L)) L)))) (S (F (S (F L (F (S (F L (S (S (F L (S (S (F L L)))))))) (F (S (F (S (F L L)) (S (F (S (S L)) L)))) (F (S (F (S (F L (F (S (F L (F (S (F L L)) L))) (S L)))) (F (S (F L (F (S (F L L)) L))) (S (S (F L (F (S (F L (F (S (F L L)) L))) (S L)))))))) (S (S (F L (S L))))))))) (S (S (F L (F (F L L) (F (S (F (S (S L)) L)) L))))))))

def prog : Tree := F (S SELF) (F L L)
-- The invariant: applied to any tree t, the loop value evaluates to a
-- function that stacks (sz t) stems onto whatever it is applied to next.
-- The match on t is the certificate's SPLIT, the quantified s its RGEN
-- residual, the recursive calls its FOLDs, and every App constructor one
-- NORMALIZE step, replayed from the program's own eager reduction.
theorem self_spec (t : Tree) :
    Exists (fun f => And (App SELF t f)
      ((s : Tree) -> App f s (stack (sz t) s))) := by
  match t with
  | leaf =>
    exact Exists.intro _ (And.intro (App.rS App.rK App.grow1 (App.r3c (App.rS (App.rS App.grow1 App.grow0 App.rK) App.grow0 (App.rS App.rK App.grow1 (App.rS App.rK (App.rS (App.rS App.rK App.grow1 App.grow0) (App.rS (App.rS App.rK (App.rS App.rK App.grow1 (App.rS App.rK App.grow0 App.grow0)) (App.rS App.rK App.grow1 (App.rS App.rK App.grow0 App.grow0))) App.grow1 App.grow1) App.grow1) App.grow1))) (App.rS App.rK App.r3a App.grow1))) (fun s => (App.rS App.rK (App.rS App.grow1 App.grow0 App.rK) App.grow0)))
  | stem u =>
    match self_spec u with
    | Exists.intro f1 (And.intro hf1a hf1b) =>
    exact Exists.intro _ (And.intro (App.rS App.rK App.grow1 (App.r3c (App.rS (App.rS App.grow1 App.grow0 App.rK) App.grow0 (App.rS App.rK App.grow1 (App.rS App.rK (App.rS (App.rS App.rK App.grow1 App.grow0) (App.rS (App.rS App.rK (App.rS App.rK App.grow1 (App.rS App.rK App.grow0 App.grow0)) (App.rS App.rK App.grow1 (App.rS App.rK App.grow0 App.grow0))) App.grow1 App.grow1) App.grow1) App.grow1))) (App.rS App.rK (App.r3b hf1a) App.grow1))) (fun s => (App.rS App.rK (hf1b s) App.grow0)))
  | fork u v =>
    match self_spec u with
    | Exists.intro f1 (And.intro hf1a hf1b) =>
    match self_spec v with
    | Exists.intro f2 (And.intro hf2a hf2b) =>
    refine Exists.intro _ (And.intro (App.rS App.rK App.grow1 (App.r3c (App.rS (App.rS App.grow1 App.grow0 App.rK) App.grow0 (App.rS App.rK App.grow1 (App.rS App.rK (App.rS (App.rS App.rK App.grow1 App.grow0) (App.rS (App.rS App.rK (App.rS App.rK App.grow1 (App.rS App.rK App.grow0 App.grow0)) (App.rS App.rK App.grow1 (App.rS App.rK App.grow0 App.grow0))) App.grow1 App.grow1) App.grow1) App.grow1))) (App.rS App.rK (App.r3c (App.rS App.rK (App.rS App.rK hf1a App.grow1) App.grow1) (App.rS (App.rS App.rK hf2a (App.rS App.rK App.grow1 (App.rS App.rK App.grow0 App.grow0))) App.rK App.grow1)) App.grow1))) (fun s => ?_))
    have h := (App.rS App.rK (App.rS App.rK (hf1b s) (hf2b (stack (sz u) s))) App.grow0)
    have e : (stack (sz v) (stack (sz u) s)) = stack (sz u + sz v) s := by
      simp only [stack_stack, sz_stack, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm]
    rw [e] at h
    exact h
termination_by sz t
decreasing_by all_goals (simp only [sz, sz_stack]; omega)

theorem prog_computes_size (t : Tree) :
    App prog t (snat (sz t)) := by
  match self_spec t with
  | Exists.intro f (And.intro h1 h2) => exact App.rS h1 App.rK (h2 leaf)

theorem prog_unique {t r : Tree}
    (h : App prog t r) : r = snat (sz t) :=
  App.det h (prog_computes_size t)
